(() => {
  const KEY = 'it-academy-v4';
  const $ = (selector, root = document) => root.querySelector(selector);
  const esc = value => String(value ?? '').replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const uid = () => `id-${Math.random().toString(36).slice(2, 10)}`;
  const coursesSeed = [
    {id:'react',name:'React және веб-интерфейс',icon:'⚛️',category:'Frontend',level:'Орташа',lessons:['React негіздері','Компоненттер мен props','State және оқиғалар','Hooks: useState, useEffect','React Router','Қорытынды жоба'],description:'Заманауи веб-қосымшалар жасап, интерфейс құруды үйреніңіз.'},
    {id:'node',name:'Node.js және API',icon:'🟩',category:'Backend',level:'Орташа',lessons:['Node.js ортасы','Express сервері','REST API жобалау','Дерекқормен жұмыс','JWT авторизациясы','API жобасы'],description:'Серверлік бағдарламалау мен REST API құрудың негізгі жолдары.'},
    {id:'flutter',name:'Flutter мобильді әзірлеу',icon:'📱',category:'Mobile',level:'Бастапқы',lessons:['Dart тіліне кіріспе','Widget құрастыру','Экрандар мен навигация','State басқару','API-мен байланыс','Мобильді жоба'],description:'Flutter және Dart арқылы Android пен iOS-қа ортақ қолданба жасаңыз.'},
    {id:'java',name:'Java және Spring Boot',icon:'☕',category:'Backend',level:'Жоғары',lessons:['Java синтаксисі','OOP қағидалары','Коллекциялар','Spring Boot негіздері','Қауіпсіз REST API','Қорытынды жоба'],description:'Java тіліндегі объектіге бағытталған бағдарламалау және сервер құру.'},
    {id:'data',name:'Дерекқор және SQL',icon:'🗄️',category:'Деректер',level:'Бастапқы',lessons:['Реляциялық дерекқор','SELECT және сүзгі','JOIN сұраулары','Кесте байланыстары','Индекстер мен оңтайландыру','PostgreSQL жобасы'],description:'SQL арқылы деректерді сақтау, байланыстыру және тиімді сұрау.'},
    {id:'uiux',name:'UI/UX және Figma',icon:'🎨',category:'Дизайн',level:'Бастапқы',lessons:['Дизайн негіздері','Пайдаланушы жолы','Wireframe құру','Figma компоненттері','Прототип және тексеру','Портфолио жобасы'],description:'Пайдаланушыға ыңғайлы интерфейс пен интерактив прототип жасаңыз.'}
  ];
  const usersSeed = [
    {id:'u-admin',name:'Академия әкімшісі',email:'admin@it.kz',password:'admin123',role:'Admin'},
    {id:'u-teacher',name:'Асқар Мұғалім',email:'teacher@it.kz',password:'teacher123',role:'Teacher'},
    {id:'u-aidana',name:'Айдана Серік',email:'student@it.kz',password:'student123',role:'Student'},
    {id:'u-nurlan',name:'Нұрлан Омар',email:'nurlan@it.kz',password:'pass1234',role:'Student'},
    {id:'u-aruzhan',name:'Аружан Қасым',email:'aruzhan@it.kz',password:'pass1234',role:'Student'}
  ];
  const fresh = () => ({users:usersSeed,courses:coursesSeed,enrollments:[
    {user:'u-aidana',course:'react',done:[0,1,2]},{user:'u-aidana',course:'data',done:[0,1,2,3]},
    {user:'u-nurlan',course:'react',done:[0,1]},{user:'u-nurlan',course:'node',done:[0,1,2]},
    {user:'u-aruzhan',course:'flutter',done:[0,1,2]}
  ],tasks:[
    {id:'task-1',course:'react',title:'Компоненттер жинағы',description:'Өзіңіздің компоненттеріңізді және оларды қолданатын бет жасаңыз.',points:30,due:'2026-10-20'},
    {id:'task-2',course:'node',title:'REST API әзірлеу',description:'Үш маршруттан тұратын қарапайым REST API дайындаңыз.',points:50,due:'2026-10-24'},
    {id:'task-3',course:'data',title:'SQL сұраулары',description:'JOIN қолданып, кестелерден есеп шығарыңыз.',points:30,due:'2026-10-22'}
  ],submissions:[{id:'sub-1',task:'task-3',user:'u-aidana',note:'Сұраулар дайын, нәтижесі тіркелді.',grade:28}],tests:{react:{'u-aidana':{score:2,total:3}}},projects:[
    {id:'proj-1',user:'u-aidana',title:'Student Planner',stack:'React, Node.js, PostgreSQL',description:'Оқу жоспары мен тапсырмаларды бақылауға арналған қосымша.'},
    {id:'proj-2',user:'u-aruzhan',title:'Campus Map',stack:'Flutter, Firebase',description:'Кампус ішіндегі орындарды көрсететін мобильді карта.'}
  ],messages:[{id:'msg-1',from:'u-teacher',to:'u-aidana',text:'Айдана, SQL тапсырмаң жақсы орындалған. Жалғастыра бер!',time:Date.now()-86400000}]});
  let db, me = null, page = 'dashboard', selectedCourse = '', selectedTask = '', authMode = 'login', searchTerm = '', categoryFilter = 'Барлығы', toastTimer;
  try { db = JSON.parse(localStorage.getItem(KEY)); } catch (_) { db = null; }
  if (!db || !Array.isArray(db.users) || !Array.isArray(db.courses)) { db = fresh(); save(); }
  function save(){ try{localStorage.setItem(KEY,JSON.stringify(db));}catch(_){showToast('Браузер деректерді сақтай алмады.');} }
  function user(id){return db.users.find(item=>item.id===id)||{name:'Белгісіз қолданушы',role:'Student'};}
  function course(id){return db.courses.find(item=>item.id===id);}
  function enrolled(userId=me?.id,courseId){return db.enrollments.find(item=>item.user===userId&&(!courseId||item.course===courseId));}
  function pct(userId,courseId){const c=course(courseId),e=enrolled(userId,courseId);return c&&e?Math.round(e.done.length/c.lessons.length*100):0;}
  function xp(userId){return db.enrollments.filter(e=>e.user===userId).reduce((n,e)=>n+e.done.length*10,0)+db.submissions.filter(s=>s.user===userId).reduce((n,s)=>n+20+(s.grade||0),0)+Object.values(db.tests).reduce((n,records)=>n+(records[userId]?.score||0)*10,0);}
  function showToast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2400);}
  function button(label,action,kind=''){return `<button class="btn ${kind}" data-action="${action}">${label}</button>`;}
  function progress(value){return `<div class="progress-track"><div class="progress-fill" style="width:${value}%"></div></div>`;}
  function heading(title,subtitle='',action=''){return `<div class="page-heading"><div><div class="eyebrow">IT ACADEMY · 4 КУРС</div><h1>${title}</h1>${subtitle?`<p>${subtitle}</p>`:''}</div>${action?`<div class="heading-actions">${action}</div>`:''}</div>`;}
  const nav=[['dashboard','⌂','Басты бет'],['courses','▦','Курстар'],['tasks','✓','Тапсырмалар'],['tests','◉','Тесттер'],['projects','◇','Жобалар'],['rating','♙','Студенттер рейтингі'],['progress','↗','Оқу барысы'],['certs','✦','Сертификаттар'],['messages','✉','Хабарламалар'],['profile','○','Профиль']];
  function render(){const root=$('#app');if(!me){root.innerHTML=auth();return;}const admin=me.role==='Admin';root.innerHTML=`<div class="overlay" data-action="close-menu"></div><div class="layout"><aside class="sidebar"><div class="brand"><div class="brand-mark">IT</div><div>IT Academy<small>4 курс · оқу платформасы</small></div></div><div class="nav-label">ОҚУ</div>${nav.slice(0,5).map(item=>navItem(item)).join('')}<div class="nav-label">ҚАУЫМДАСТЫҚ</div>${nav.slice(5).map(item=>navItem(item)).join('')}${admin?`<div class="nav-label">БАСҚАРУ</div>${navItem(['admin','⚙','Әкімші панелі'])}`:''}<div class="sidebar-bottom"><strong>🚀 Біліміңді шыңда</strong><p>Күн сайын бір қадам алға.</p></div></aside><main class="main"><header class="topbar"><div class="top-left"><button class="icon-btn mobile-menu" data-action="menu">☰</button><span class="top-title">Оқу платформасы</span></div><div class="top-actions"><button class="icon-btn" data-action="navigate:messages" aria-label="Хабарламалар">✉</button><div class="user-info"><div class="avatar">${esc(me.name.slice(0,1).toUpperCase())}</div><div><div class="user-name">${esc(me.name)}</div><div class="user-role">${esc(roleName(me.role))}</div></div></div><button class="icon-btn" data-action="logout" aria-label="Шығу">↗</button></div></header><section class="content">${viewContent()}</section></main></div>`;}
  function navItem(item){return `<button class="nav-link ${page===item[0]?'active':''}" data-action="navigate:${item[0]}"><span class="nav-icon">${item[1]}</span>${item[2]}</button>`;}
  function roleName(role){return ({Admin:'Әкімші',Teacher:'Оқытушы',Student:'Студент'})[role]||role;}
  function auth(){return `<main class="auth-screen"><section class="auth-art"><div class="brand"><div class="brand-mark">IT</div><div>IT Academy<small>4 курс · оқу платформасы</small></div></div><div class="eyebrow">БОЛАШАҚ ОСЫ ЖЕРДЕН БАСТАЛАДЫ</div><h1>Біліміңді <em>жаңа деңгейге</em> көтер.</h1><p>Бағдарламалау, дизайн және деректер курстарын бір жерден оқып, нақты жобалар арқылы тәжірибе жина.</p><div class="auth-points"><span>✦ Практикалық сабақтар</span><span>✦ Жеке оқу барысы</span><span>✦ Жоба портфолиосы</span></div></section><section class="auth-form-wrap"><form class="auth-form" id="auth-form"><div class="eyebrow">${authMode==='login'?'ҚОШ КЕЛДІҢ':'ЖАҢА АККАУНТ'}</div><h2>${authMode==='login'?'Жүйеге кіру':'Тіркелу'}</h2><p>${authMode==='login'?'Оқуды жалғастыру үшін деректеріңізді енгізіңіз.':'Жеке аккаунт ашып, оқуды бастаңыз.'}</p>${authMode==='register'?`<div class="field"><label class="field-label" for="auth-name">Аты-жөніңіз</label><input class="input" id="auth-name" name="name" required placeholder="Аты-жөніңіз"></div>`:''}<div class="field"><label class="field-label" for="auth-email">Электрондық пошта</label><input class="input" id="auth-email" name="email" type="email" required placeholder="name@example.com"></div><div class="field"><label class="field-label" for="auth-password">Құпиясөз</label><input class="input" id="auth-password" name="password" type="password" required minlength="6" placeholder="Кемінде 6 таңба"></div><button class="btn" type="submit">${authMode==='login'?'Кіру':'Аккаунт ашу'} →</button><div class="auth-switch">${authMode==='login'?'Аккаунтыңыз жоқ па?':'Аккаунтыңыз бар ма?'} <button class="text-btn" type="button" data-action="auth-switch">${authMode==='login'?'Тіркелу':'Кіру'}</button></div>${authMode==='login'?`<div class="demo-box"><strong>Демо аккаунттар</strong><br>Әкімші: admin@it.kz / admin123<br>Оқытушы: teacher@it.kz / teacher123<br>Студент: student@it.kz / student123</div>`:''}</form></section></main>`;}
  function viewContent(){switch(page){case'dashboard':return dashboard();case'courses':return coursesView();case'course':return courseView();case'tasks':return tasksView();case'tests':return testsView();case'test':return testView();case'projects':return projectsView();case'rating':return ratingView();case'progress':return progressView();case'certs':return certsView();case'messages':return messagesView();case'profile':return profileView();case'admin':return adminView();default:return dashboard();}}
  function dashboard(){const myCourses=db.enrollments.filter(e=>e.user===me.id),avg=myCourses.length?Math.round(myCourses.reduce((n,e)=>n+pct(me.id,e.course),0)/myCourses.length):0;const next=db.tasks.filter(t=>myCourses.some(e=>e.course===t.course)).slice(0,3);return `${heading(`Сәлем, ${esc(me.name.split(' ')[0])}! 👋`,'Бүгінгі оқу мақсатыңа бір қадам жақында.') }<div class="grid"><article class="card stat-card span-4" style="--accent:var(--blue)"><span class="stat-icon">📚</span><div class="stat-label">Менің курстарым</div><div class="stat-value">${myCourses.length}</div><div class="stat-note">Белсенді оқу жолдары</div></article><article class="card stat-card span-4" style="--accent:var(--mint)"><span class="stat-icon">◉</span><div class="stat-label">Орташа прогресс</div><div class="stat-value">${avg}%</div>${progress(avg)}</article><article class="card stat-card span-4" style="--accent:var(--orange)"><span class="stat-icon">✦</span><div class="stat-label">Жинаған ұпай</div><div class="stat-value">${xp(me.id)}</div><div class="stat-note">XP · әрі қарай жалғастыр!</div></article><article class="card span-7"><div class="row"><div><h3>Оқуым</h3><span class="muted">Курстарыңдағы соңғы нәтиже</span></div>${button('Курстарды көру','navigate:courses','secondary small')}</div>${myCourses.length?myCourses.map(e=>{const c=course(e.course);return c?`<div class="lesson-row"><div class="course-icon">${c.icon}</div><div style="flex:1"><div class="row"><strong>${esc(c.name)}</strong><span class="muted">${pct(me.id,c.id)}%</span></div>${progress(pct(me.id,c.id))}</div><button class="icon-btn" data-action="open-course:${c.id}">→</button></div>`:''}).join(''):`<div class="empty"><span>📘</span>Әзірге курсқа тіркелмедің.<br>${button('Курстарды шолу','navigate:courses','small')}</div>`}</article><article class="card span-5"><div class="row"><div><h3>Жақында аяқталатын тапсырмалар</h3><span class="muted">Келесі қадамдарың</span></div></div>${next.length?next.map(t=>`<div class="task-row"><div class="task-title">${esc(t.title)}</div><div class="task-meta"><span>${esc(course(t.course)?.name||'')}</span><span>·</span><span>Мерзімі ${esc(date(t.due))}</span></div></div>`).join(''):`<div class="empty"><span>✓</span>Қазір тапсырма жоқ</div>`}</article><article class="card span-12"><div class="row"><div><h3>Апталық оқу жоспары</h3><span class="muted">Кішкентай қадамдар үлкен нәтижеге жеткізеді.</span></div><span class="chip green">${myCourses.reduce((n,e)=>n+e.done.length,0)} сабақ аяқталды</span></div>${progress(Math.min(avg,100))}</article></div>`;}
  function date(value){if(!value)return '—';return new Intl.DateTimeFormat('kk-KZ',{day:'numeric',month:'short'}).format(new Date(`${value}T12:00:00`));}
  function coursesView(){const cats=['Барлығы',...new Set(db.courses.map(c=>c.category))];const list=db.courses.filter(c=>(categoryFilter==='Барлығы'||c.category===categoryFilter)&&`${c.name} ${c.description} ${c.category}`.toLowerCase().includes(searchTerm.toLowerCase()));return `${heading('Курстар','Өзіңе керек бағытты таңдап, практикалық сабақтарға кіріс.') }<div class="filters"><input class="input" id="course-search" placeholder="Курс іздеу…" value="${esc(searchTerm)}"><select class="select" id="category-filter">${cats.map(cat=>`<option ${cat===categoryFilter?'selected':''}>${esc(cat)}</option>`).join('')}</select></div><div class="course-list">${list.length?list.map(c=>courseCard(c)).join(''):`<div class="card empty" style="grid-column:1/-1"><span>⌕</span>Іздеуге сай курс табылмады.</div>`}</div>`;}
  function courseCard(c){const e=enrolled(me.id,c.id),p=pct(me.id,c.id);return `<article class="card course-card"><div class="row"><div class="course-icon">${c.icon}</div><span class="chip">${esc(c.category)}</span></div><div><h3>${esc(c.name)}</h3><p>${esc(c.description)}</p></div><div class="course-meta"><span>${c.lessons.length} сабақ</span><span>${esc(c.level)}</span></div>${e?`<div>${progress(p)}<div class="course-meta" style="margin-top:6px"><span>Оқу барысы</span><b>${p}%</b></div></div>`:''}<div class="course-footer">${button(e?'Курсты жалғастыру':'Курсқа тіркелу',`${e?'open-course':'enroll'}:${c.id}`,e?'secondary':'')}</div></article>`;}
  function courseView(){const c=course(selectedCourse);if(!c)return coursesView();const e=enrolled(me.id,c.id),done=e?.done||[];return `${heading(c.name,`${esc(c.category)} · ${c.lessons.length} сабақ · ${esc(c.level)}`,button('← Курстарға қайту','navigate:courses','secondary'))}<div class="grid"><article class="card span-8"><div class="row"><div><div class="eyebrow">${c.icon} КУРС МАЗМҰНЫ</div><h3 style="margin-top:7px">Сабақтар</h3></div><span class="chip green">${pct(me.id,c.id)}% орындалды</span></div>${progress(pct(me.id,c.id))}${c.lessons.map((lesson,i)=>`<label class="lesson-row"><input type="checkbox" class="lesson-check" data-action="lesson:${c.id}:${i}" ${done.includes(i)?'checked':''} ${e?'':'disabled'}><span class="lesson-number">${String(i+1).padStart(2,'0')}</span><span class="lesson-name">${esc(lesson)}</span><span class="muted">${done.includes(i)?'✓':'○'}</span></label>`).join('')}</article><article class="card span-4"><div class="course-icon">${c.icon}</div><h3 style="margin-top:14px">Курс туралы</h3><p class="muted">${esc(c.description)}</p><div class="task-row"><span class="muted">Бағыт</span><strong>${esc(c.category)}</strong></div><div class="task-row"><span class="muted">Деңгей</span><strong>${esc(c.level)}</strong></div>${!e&&me.role==='Student'?button('Курсқа тіркелу',`enroll:${c.id}`):`<p class="muted">Сабақтарды белгілеген сайын оқу прогресі жаңарып отырады.</p>`}</article></div>`;}
  function tasksView(){const isStudent=me.role==='Student';const list=db.tasks.filter(t=>!isStudent||enrolled(me.id,t.course));return `${heading('Тапсырмалар','Тәжірибе жинап, біліміңді нақты жұмыспен бекіт.')}${!isStudent?`<article class="card" style="margin-bottom:15px"><h3>Жаңа тапсырма</h3><form id="task-form" class="form-row"><label class="field"><span class="field-label">Курс</span><select class="select" name="course">${db.courses.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label><label class="field"><span class="field-label">Тапсырма атауы</span><input class="input" name="title" required placeholder="Мысалы: API құру"></label><label class="field"><span class="field-label">Ұпай</span><input class="input" name="points" type="number" min="1" value="30"></label><button class="btn" type="submit">Тапсырма қосу</button></form></article>`:''}<div class="card">${list.length?list.map(t=>{const c=course(t.course),sub=db.submissions.find(s=>s.task===t.id&&s.user===me.id);return `<div class="task-row"><div class="row stack-mobile"><div><div class="task-title">${esc(t.title)}</div><div class="task-meta"><span>${esc(c?.name||'')}</span><span>·</span><span>${t.points} ұпай</span><span>·</span><span>Мерзімі ${date(t.due)}</span></div><p class="muted">${esc(t.description)}</p>${sub?`<span class="chip ${sub.grade!==null?'green':'orange'}">${sub.grade!==null?`Баға: ${sub.grade}`:'Тексерілуде'}</span>`:''}</div><div class="task-actions">${isStudent?button(sub?'Жаңарту':'Жауап жіберу',`submit-task:${t.id}`,sub?'secondary small':'small'):teacherTaskAction(t)}</div></div></div>`;}).join(''):`<div class="empty"><span>✓</span>${isStudent?'Қолжетімді тапсырма әзірге жоқ. Курсқа тіркеліп көр.':'Әзірге тапсырма қосылмаған.'}</div>`}</div>`;}
  function teacherTaskAction(t){const subs=db.submissions.filter(s=>s.task===t.id);return `<details><summary class="chip" style="cursor:pointer">${subs.length} жауап</summary>${subs.map(s=>`<form class="grade-form task-meta" data-submission="${s.id}" style="margin-top:9px"><span>${esc(user(s.user).name)}: ${esc(s.note)}</span><input class="input" name="grade" type="number" min="0" max="${t.points}" value="${s.grade??''}" placeholder="Баға" style="width:85px"><button class="btn small" type="submit">Бағалау</button></form>`).join('')||'<p class="muted">Жауап әлі жоқ.</p>'}</details>`;}
  function testsView(){const available=db.courses.filter(c=>me.role!=='Student'||enrolled(me.id,c.id));return `${heading('Білімді тексер','Курсқа тіркелген соң қысқа тест тапсырып, нәтижені бірден көр.') }<div class="course-list">${available.length?available.map(c=>{const result=db.tests[c.id]?.[me.id];return `<article class="card course-card"><div class="row"><div class="course-icon">◉</div><span class="chip">${c.lessons.length} сұрақ</span></div><div><h3>${esc(c.name)} · тест</h3><p>Тақырыптарды бекітуге арналған шағын тексеру.</p></div>${result?`<span class="chip green">Соңғы нәтиже: ${result.score}/${result.total}</span>`:''}<div class="course-footer">${me.role==='Student'?button(result?'Қайта тапсыру':'Тестті бастау',`open-test:${c.id}`):'<span class="muted">Студенттерге арналған</span>'}</div></article>`;}).join(''):`<div class="card empty" style="grid-column:1/-1"><span>◉</span>Тесттерді көру үшін курсқа тіркеліңіз.</div>`}</div>`;}
  const quizBank={react:[['React-та күйді сақтау үшін қай hook қолданылады?',['useState','useRoute','useFile'],0],['Тізім элементіне тұрақты сәйкестендіргіш не үшін керек?',['key','href','alt'],0],['useEffect қай кезде іске қосылады?',['Компонент көрсетілгеннен кейін','Тек CSS өзгергенде','Тек серверде'],0]],node:[['Express дегеніміз не?',['Node.js веб-фреймворкі','Дерекқор тілі','Браузер'],0],['HTTP GET сұрауы әдетте не істейді?',['Дерек алады','Жаңа файл жояды','Қолданбаны жабады'],0],['JWT көбіне не үшін қолданылады?',['Авторизация дерегін тасымалдау','Стиль жазу','Сурет салу'],0]],data:[['SQL-де кестеден жол таңдайтын команда?',['SELECT','PAINT','MOVE'],0],['JOIN не үшін керек?',['Кестелер дерегін байланыстыру','Құпиясөзді көрсету','Баған түсін өзгерту'],0],['PRIMARY KEY мақсаты?',['Жолды бірегей анықтау','Кестені жасыру','Дерек экспорттау'],0]]};
  function quiz(c){return quizBank[c.id]||[['Бағдарламалауда алгоритм деген не?',['Қадамдар тізбегі','Сурет форматы','Пернетақта түрі'],0],['Қолданбаны тексеру не үшін керек?',['Қателерді анықтау','Экран түсін өзгерту','Файл қысу'],0],['Нұсқа бақылау құралының мысалы?',['Git','Paint','Clock'],0]];}
  function testView(){const c=course(selectedCourse);if(!c)return testsView();return `${heading(`${c.name} · тест`,'Дұрыс жауапты таңда. Нәтиже тапсырғаннан кейін көрсетіледі.',button('← Тесттерге қайту','navigate:tests','secondary'))}<form id="quiz-form" data-course="${c.id}">${quiz(c).map((q,i)=>`<article class="card" style="margin-bottom:13px"><h3>${i+1}. ${esc(q[0])}</h3>${q[1].map((option,j)=>`<label class="test-option"><input required type="radio" name="q${i}" value="${j}"><span>${esc(option)}</span></label>`).join('')}</article>`).join('')}${button('Нәтижені көру','submit-quiz')}</form>`;}
  function projectsView(){return `${heading('Жобалар','Өз жұмыстарыңды көрсетіп, портфолио жина.')}${me.role==='Student'?`<article class="card" style="margin-bottom:15px"><h3>Жаңа жоба қосу</h3><form id="project-form"><div class="form-row"><label class="field"><span class="field-label">Жоба атауы</span><input class="input" name="title" required placeholder="Мысалы: Менің портфолиом"></label><label class="field"><span class="field-label">Технологиялар</span><input class="input" name="stack" placeholder="React, Firebase"></label></div><div class="field"><label class="field-label">Сипаттама</label><textarea class="textarea" name="description" rows="2" style="width:100%" placeholder="Жоба не істейді?"></textarea></div><button class="btn" type="submit">Жобаны қосу</button></form></article>`:''}<div class="course-list">${db.projects.length?db.projects.map(p=>`<article class="card course-card"><div class="course-icon">◇</div><div><h3>${esc(p.title)}</h3><p>${esc(p.description)}</p></div><span class="chip">${esc(p.stack||'Технология көрсетілмеген')}</span><div class="row"><span class="muted">Автор: ${esc(user(p.user).name)}</span>${(p.user===me.id||me.role==='Admin')?button('Өшіру',`delete-project:${p.id}`,'danger small'):''}</div></article>`).join(''):`<div class="card empty" style="grid-column:1/-1"><span>◇</span>Әзірге жоба жоқ.</div>`}</div>`;}
  function ratingView(){const students=db.users.filter(u=>u.role==='Student').map(u=>({...u,points:xp(u.id)})).sort((a,b)=>b.points-a.points);return `${heading('Студенттер рейтингі','Оқу жетістіктері мен жинаған ұпайлар.') }<div class="card table-wrap"><table><thead><tr><th>Орын</th><th>Студент</th><th>Курстар</th><th>Оқу прогресі</th><th>XP</th></tr></thead><tbody>${students.map((s,i)=>{const es=db.enrollments.filter(e=>e.user===s.id),avg=es.length?Math.round(es.reduce((n,e)=>n+pct(s.id,e.course),0)/es.length):0;return `<tr><td class="rank">${['🥇','🥈','🥉'][i]||i+1}</td><td>${esc(s.name)} ${s.id===me.id?'<span class="chip">Сіз</span>':''}</td><td>${es.length}</td><td style="min-width:150px">${progress(avg)}<small class="muted">${avg}%</small></td><td><strong>${s.points}</strong></td></tr>`;}).join('')}</tbody></table></div>`;}
  function progressView(){if(me.role!=='Student')return `${heading('Оқу барысы','Студенттердің курстар бойынша жалпы нәтижесі.') }<div class="card table-wrap"><table><thead><tr><th>Студент</th>${db.courses.map(c=>`<th>${esc(c.name)}</th>`).join('')}</tr></thead><tbody>${db.users.filter(u=>u.role==='Student').map(u=>`<tr><td>${esc(u.name)}</td>${db.courses.map(c=>`<td>${enrolled(u.id,c.id)?pct(u.id,c.id)+'%':'—'}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;const list=db.enrollments.filter(e=>e.user===me.id);return `${heading('Оқу барысы','Әр курстағы үлгерімің мен аяқталған сабақтар.') }<div class="grid">${list.length?list.map(e=>{const c=course(e.course),p=pct(me.id,e.course);return `<article class="card span-6"><div class="row"><div><h3>${c.icon} ${esc(c.name)}</h3><span class="muted">${e.done.length}/${c.lessons.length} сабақ аяқталды</span></div><strong>${p}%</strong></div>${progress(p)}<p class="muted">${p===100?'Керемет! Сертификатың дайын.':'Келесі сабақты жалғастыр.'}</p>${button('Курсты ашу',`open-course:${c.id}`,'secondary small')}</article>`;}).join(''):`<div class="card empty span-12"><span>↗</span>Оқу барысын бастау үшін курсқа тіркел.</div>`}</div>`;}
  function certsView(){const complete=db.enrollments.filter(e=>e.user===me.id&&pct(me.id,e.course)===100);return `${heading('Сертификаттар','Курстың барлық сабағын аяқтағанда сертификат осында пайда болады.') }${complete.length?`<div class="course-list">${complete.map(e=>`<article class="card certificate"><div><div class="seal">✦</div><div class="eyebrow">IT ACADEMY · СЕРТИФИКАТ</div><h2>${esc(course(e.course).name)}</h2><div class="name">${esc(me.name)}</div><p class="muted">Курсты толық аяқтағаны үшін берілді</p><button class="btn secondary small" data-action="print">Басып шығару</button></div></article>`).join('')}</div>`:`<div class="card empty"><span>✦</span>Сертификат алу үшін бір курстың барлық сабағын аяқта.<br>${button('Оқу барысын көру','navigate:progress','secondary small')}</div>`}`;}
  function messagesView(){const list=db.messages.filter(m=>m.from===me.id||m.to===me.id).sort((a,b)=>b.time-a.time);return `${heading('Хабарламалар','Оқытушымен және топтастарыңмен байланыс.') }<article class="card" style="margin-bottom:15px"><form id="message-form"><div class="form-row"><label class="field"><span class="field-label">Кімге</span><select class="select" name="to">${db.users.filter(u=>u.id!==me.id).map(u=>`<option value="${u.id}">${esc(u.name)} · ${roleName(u.role)}</option>`).join('')}</select></label><label class="field" style="flex:3"><span class="field-label">Хабарлама</span><input class="input" name="text" required placeholder="Хабарлама мәтіні"></label><button class="btn" type="submit">Жіберу</button></div></form></article><article class="card">${list.length?list.map(m=>`<div class="message-row"><div class="row"><strong>${m.from===me.id?`Сіз → ${esc(user(m.to).name)}`:`${esc(user(m.from).name)} → Сіз`}</strong><small class="muted">${new Intl.DateTimeFormat('kk-KZ',{dateStyle:'medium',timeStyle:'short'}).format(new Date(m.time))}</small></div><p>${esc(m.text)}</p></div>`).join(''):`<div class="empty">Хабарлама әлі жоқ.</div>`}</article>`;}
  function profileView(){return `${heading('Профиль','Жеке деректерің мен аккаунт баптаулары.') }<article class="card" style="max-width:640px"><div class="row" style="justify-content:flex-start;margin-bottom:20px"><div class="avatar" style="width:55px;height:55px;font-size:20px">${esc(me.name.slice(0,1))}</div><div><h3>${esc(me.name)}</h3><span class="chip">${roleName(me.role)}</span></div></div><form id="profile-form"><div class="field"><label class="field-label">Аты-жөні</label><input class="input" name="name" required value="${esc(me.name)}" style="width:100%"></div><div class="field"><label class="field-label">Электрондық пошта</label><input class="input" value="${esc(me.email)}" disabled style="width:100%"></div><button class="btn" type="submit">Өзгерісті сақтау</button></form></article>`;}
  function adminView(){if(me.role!=='Admin')return dashboard();return `${heading('Әкімші панелі','Қолданушылар мен оқу курстарын басқар.') }<article class="card" style="margin-bottom:15px"><h3>Қолданушылар</h3><div class="table-wrap"><table><thead><tr><th>Аты-жөні</th><th>Email</th><th>Рөлі</th></tr></thead><tbody>${db.users.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.email)}</td><td><select class="select" data-action="role:${u.id}">${[['Student','Студент'],['Teacher','Оқытушы'],['Admin','Әкімші']].map(([v,l])=>`<option value="${v}" ${u.role===v?'selected':''}>${l}</option>`).join('')}</select></td></tr>`).join('')}</tbody></table></div></article><article class="card"><h3>Жаңа курс</h3><form id="course-form" class="form-row"><label class="field"><span class="field-label">Курс атауы</span><input class="input" name="name" required></label><label class="field"><span class="field-label">Бағыт</span><input class="input" name="category" required placeholder="Frontend"></label><label class="field"><span class="field-label">Белгіше</span><input class="input" name="icon" value="💻" maxlength="4"></label><button class="btn" type="submit">Курс қосу</button></form></article>`;}
  function navigate(target){page=target;selectedCourse='';selectedTask='';searchTerm='';categoryFilter='Барлығы';render();window.scrollTo(0,0);}
  function enroll(id){if(!enrolled(me.id,id)){db.enrollments.push({user:me.id,course:id,done:[]});save();showToast('Курсқа сәтті тіркелдің!');}selectedCourse=id;page='course';render();}
  function submitTask(id){const task=db.tasks.find(t=>t.id===id);if(!task)return;const note=prompt(`${task.title}\nЖауабың немесе жобаның сілтемесі:`);if(note===null)return;if(!note.trim()){showToast('Жауап мәтінін енгізіңіз.');return;}const existing=db.submissions.find(s=>s.task===id&&s.user===me.id);if(existing){existing.note=note;existing.grade=null;}else db.submissions.push({id:uid(),task:id,user:me.id,note,grade:null});save();showToast('Жауап оқытушыға жіберілді.');render();}
  function formData(form){return Object.fromEntries(new FormData(form).entries());}
  $('#app').addEventListener('click',event=>{const target=event.target.closest('[data-action]');if(!target)return;const action=target.dataset.action;if(action==='auth-switch'){authMode=authMode==='login'?'register':'login';render();}else if(action==='logout'){me=null;page='dashboard';render();}else if(action==='menu'){$('.sidebar')?.classList.toggle('open');$('.overlay')?.classList.toggle('show');}else if(action==='close-menu'){$('.sidebar')?.classList.remove('open');$('.overlay')?.classList.remove('show');}else if(action.startsWith('navigate:'))navigate(action.split(':')[1]);else if(action.startsWith('open-course:')){selectedCourse=action.split(':')[1];page='course';render();}else if(action.startsWith('enroll:'))enroll(action.split(':')[1]);else if(action.startsWith('submit-task:'))submitTask(action.split(':')[1]);else if(action.startsWith('open-test:')){selectedCourse=action.split(':')[1];page='test';render();}else if(action==='submit-quiz'){$('#quiz-form').requestSubmit();}else if(action.startsWith('delete-project:')){if(confirm('Бұл жобаны өшіресіз бе?')){db.projects=db.projects.filter(p=>p.id!==action.split(':')[1]);save();render();}}else if(action==='print')window.print();});
  $('#app').addEventListener('change',event=>{const el=event.target,action=el.dataset.action||'';if(action.startsWith('lesson:')){const[,courseId,index]=action.split(':'),e=enrolled(me.id,courseId),i=Number(index);if(!e){showToast('Алдымен курсқа тіркеліңіз.');render();return;}e.done.includes(i)?e.done=e.done.filter(n=>n!==i):e.done.push(i);save();render();}else if(action.startsWith('role:')){if(me.role!=='Admin')return;const u=user(action.split(':')[1]);u.role=el.value;save();showToast('Қолданушы рөлі жаңартылды.');}else if(el.id==='category-filter'){categoryFilter=el.value;render();}});
  $('#app').addEventListener('input',event=>{if(event.target.id==='course-search'){searchTerm=event.target.value;const cursor=event.target.selectionStart;render();const replacement=$('#course-search');replacement.focus();replacement.setSelectionRange(cursor,cursor);}});
  $('#app').addEventListener('submit',event=>{const form=event.target;event.preventDefault();const data=formData(form);if(form.classList.contains('grade-form')){if(me.role==='Student')return;const sub=db.submissions.find(item=>item.id===form.dataset.submission);if(sub){sub.grade=Math.min(Number(data.grade)||0,db.tasks.find(t=>t.id===sub.task)?.points||100);save();showToast('Тапсырма бағаланды.');render();}}else if(form.id==='auth-form'){const email=data.email.trim().toLowerCase();if(authMode==='login'){const found=db.users.find(u=>u.email.toLowerCase()===email&&u.password===data.password);if(!found){showToast('Email немесе құпиясөз қате.');return;}me=found;}else{if(db.users.some(u=>u.email.toLowerCase()===email)){showToast('Бұл email тіркелген.');return;}me={id:uid(),name:data.name.trim(),email,password:data.password,role:'Student'};db.users.push(me);}save();page='dashboard';render();}else if(form.id==='task-form'){db.tasks.push({id:uid(),course:data.course,title:data.title.trim(),description:'Оқытушы тапсырмасы',points:Number(data.points)||30,due:''});save();showToast('Тапсырма қосылды.');render();}else if(form.id==='project-form'){db.projects.unshift({id:uid(),user:me.id,title:data.title.trim(),stack:data.stack.trim(),description:data.description.trim()});save();showToast('Жоба портфолиоға қосылды.');render();}else if(form.id==='message-form'){db.messages.unshift({id:uid(),from:me.id,to:data.to,text:data.text.trim(),time:Date.now()});save();showToast('Хабарлама жіберілді.');render();}else if(form.id==='profile-form'){me.name=data.name.trim();save();showToast('Профиль жаңартылды.');render();}else if(form.id==='course-form'){db.courses.push({id:uid(),name:data.name.trim(),icon:data.icon||'💻',category:data.category.trim(),level:'Бастапқы',lessons:['Кіріспе','Негізгі ұғымдар','Практикалық жұмыс'],description:'Оқу бағдарламасына жаңа курс қосылды.'});save();showToast('Курс қосылды.');render();}else if(form.id==='quiz-form'){const id=form.dataset.course,questions=quiz(course(id));let score=0;questions.forEach((q,i)=>{if(Number(data[`q${i}`])===q[2])score++;});db.tests[id]??={};db.tests[id][me.id]={score,total:questions.length};save();showToast(`Нәтижең: ${score}/${questions.length}`);page='tests';render();}});
  document.addEventListener('keydown',event=>{if(event.key==='Escape'){$('.sidebar')?.classList.remove('open');$('.overlay')?.classList.remove('show');}});
  render();
})();
